### ISSUE TITLE
Update tutorials?

### ISSUE THREAD

**Issue by jma7** [vatlab/vat-docs#14]
Just wonder should we update the tutorials too? The origin of some of the datasets is not very clear, may need update too. @BoPeng

**Comment by BoPeng** [comment]
Yes but with updated data. Please mark the tutorial as outdated (pending) if you cannot find the source.

**Comment by BoPeng** [comment]
`development\manage_resource.py --upload` but currently only me (faculty) is allowed to write to `bcb_web`.

**Comment by BoPeng** [comment]
Note that for whatever new snapshot you create, you should put `v3` somewhere to differentiate them from the old snapshots. Replacing the old one is not safe because v2 users might still use them.

**Comment by HenryLeongStat** [comment]
Need to upload new snapshots to the repository.

**Comment by HenryLeongStat** [comment]
@BoPeng will upload.
