### ISSUE TITLE
Init page-> Examples: create subprojects from the parent project

### ISSUE THREAD

**Issue by tutudong** [vatlab/vat-docs#15]
```
$CEU iceli$ vtools show genotypes
ERROR: Unsupported genotype storage model None
```

**Comment by BoPeng** [comment]
@jma7 the `Project` class should define a storage model w/wo the environment variable, right? I think we can make HDF5 the default if no environment variable is defined.

**Comment by jma7** [comment]
The default storage mode is HDF5 now. Updated "Examples: create a parent project" to use another dataset. 
Added test to show that "Examples: create subprojects from the parent project" and "Create a project from several subprojects" is only available for SQLite version.
