### ISSUE TITLE
command update 2.1->Examples: adding annotation info from ANNOVAR output 

### ISSUE THREAD

**Issue by tutudong** [vatlab/vat-docs#16]
```
 $vtools annotate_variation.pl ann.in humandb/
usage: vtools [-h] [--version]
              {init,import,phenotype,show,liftover,use,update,select,exclude,compare,output,export,remove,associate,admin,execute}
              ...
vtools: error: invalid choice: 'annotate_variation.pl' (choose from 'init', 'import', 'phenotype', 'show', 'liftover', 'use', 'update', 'select', 'exclude', 'compare', 'output', 'export', 'remove', 'associate', 'admin', 'execute')
```

**Comment by BoPeng** [comment]
Should be `perl annotate_variation.pl...`

**Comment by tutudong** [comment]
Then
Can't open perl script "annotate_variation.pl": No such file or directory

**Comment by BoPeng** [comment]
This belongs to the ANNOVAR package. You will need to install it,

**Comment by tutudong** [comment]
After changing `vtools import V*.vcf --build hg18` to `vtools import V*.vcf --build hg38`

$update iceli$ vtools use dbSNP-hg38_130
ERROR: Annotation database dbSNP-hg38_130 not found.
$update iceli$ vtools use dbSNP-hg18_130
INFO: Downloading annotation database annoDB/dbSNP-hg18_130.ann
ERROR: Annotation database cannot be used because it is based on a reference genome that is different from the one used by the project. Please use a version of annotation databse for the project (vtools show annotations), or liftover the existing project (vtoos liftover) to make it compatible with the annotation database.
