### ISSUE TITLE
update text content

### ISSUE THREAD

**Issue by jma7** [vatlab/vat-docs#18]
I made some new data files to be used in the documents. It seems to me some text contents in the documents needs to be updated too. For example, in the documents for import, some description is for SQLite version. Do you want to emphasize different format of input files at the beginning or maybe move that part to a later section? Do you want the documents concentrating on importing VCFs? @BoPeng

**Comment by BoPeng** [comment]
Yes, I think it makes sense to concentrate on VCF format and the HDF5 storage.
