### ISSUE TITLE
cannot generate the correct table with hugo

### ISSUE THREAD

**Issue by BingLi17** [vatlab/vat-docs#29]
[](https://vatlab.github.io/vat-docs/documentation/customization/format/supportedformats/)

The table is messy. @jma7 Could you help me with this?

**Comment by jma7** [comment]
Which table?

**Comment by BingLi17** [comment]
Sorry. 

[](https://vatlab.github.io/vat-docs/documentation/customization/format/supportedformats/)

**Comment by BingLi17** [comment]
Sorry.

https://vatlab.github.io/vat-docs/documentation/customization/format/supportedformats/

**Comment by jma7** [comment]
Done.
